### ISSUE TITLE
use null or empty object instead of an empty string if result object is null

### ISSUE THREAD

**Issue by AllenFang** [jackyoh/marathon-eventlog-restful#1]
For example, check your code [here](https://github.com/jackyoh/marathon-eventlog-restful/blob/master/src/main/java/com/island/resource/EventLogResource.java#L103)

if there's no any data for an object, it is supposed to be output null or even an empty object instead of an empty string

Like following will be better?, maybe you can consider about it
```java

// Null Object Support
Gson gson = new GsonBuilder().serializeNulls().create();

if(taskStatus == null){
   LOGGER.info(appId + " application status is not found");
   return gson.toJson(taskStatus);
}
```

**Comment by jackyoh** [comment]
I modify the code for null result in the dev branch.
Thank you for your suggestion!

**Comment by AllenFang** [comment]
BTW, Your avatar is pretty cool
